 const ADD_TODO = 'ADD_TODO'
 const TOGGLE_TODO = 'TOGGLE_TODO'
 const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
 const NEW_TASK_ADDED = 'NEW_TASK_ADDED'
 const TASK_DESCRIPTION_INSERTED = 'TASK_DESCRIPTION_INSERTED'
 const TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED'
 const RESET_TASK_INPUT = 'RESET_TASK_INPUT'

 export default actionTypes = {
   ADD_TODO,
   TOGGLE_TODO,
   SET_VISIBILITY_FILTER,
   NEW_TASK_ADDED,
   TASK_DESCRIPTION_INSERTED,
   TASK_STATUS_CHANGED,
   RESET_TASK_INPUT
 }
